# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12457e04c6e1602f9a705f488b77a83aa5ce14c48f512c80270a7bf8592308fb06e5f5f0daf89137622250ec8c673e426ee7c7c0eb94df83aa26574af6900194

test:
  secret_key_base: c3e50be590856d1e4292a9e407619d0a6d44ded8755089da24da161de683e68f444819a8fc19d8614c1c1c0e01301226cfd4cb4e87a40b0912b6e135909dba57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
